# **Курс "Програмування на мові Python"**

## **Практичне зайняття №9**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи правило перестановок.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажанням можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [9]:
import numpy as np
import itertools

def random_matrix(dim):
    """
    The function generates dim x dim array of integers
    between 0 and 10.
    """
    matrix = np.random.randint(10, size = (dim, dim))
    return matrix

#Example of using permutations() method
t = list(itertools.permutations('123', 3))

while True:
    try:
        dim = input('Введіть розмірність матриці: ')
        dim = int(dim)
        if dim > 0:
            matrix = random_matrix(dim)
            print('Згенерована матриця: ')
            print(f'{matrix}')
            break
        else:
            print('Розмірність має бути додатнім числом')
            continue
    except ValueError:
        print('Розмірність матриці має бути цілим числом')
        continue 
    
def create_permutations(dim):
    '''
    Генерація списку перестановок
    '''
    dim = list(itertools.permutations(range(dim)))
    return dim

def product(matrix, permutation):
    '''
    Обчислення добутку та знаходження знака
    '''
    multiple = 1
    for m, n in enumerate(permutation):
        multiple = multiple * matrix[m][n]
    sign = 1
    for i in range(len(permutation)):
        for j in range(i + 1, len(permutation)):
            if permutation[i] > permutation[j]:
                sign *= -1
    return sign * multiple

def elements_sum(matrix):
    '''
    Обчислення визначника матриці (сума добутків перестановок)
    '''
    dim = len(matrix)
    permutations = create_permutations(dim)
    elem_sum = sum(product(matrix, permutation) for permutation in permutations)
    return elem_sum

print(f'Визначник матриці: {elements_sum(matrix)}')






Згенерована матриця: 
[[7 9 7]
 [7 9 8]
 [8 6 8]]
Визначник матриці: 30
